// 放置路徑：src/app/export/conversation/[id]/page.tsx
//
// v1.3.5 新增：print-friendly conversation export 頁面
//
// 使用：開新 tab 到 /export/conversation/xxx?autoprint=1
//   → user 看到漂亮排版的對話、瀏覽器自動 trigger Cmd+P 列印 dialog
//   → user 在列印 dialog 選「另存為 PDF」
//
// 設計：
//   - Header：羽升 brand + 主題標題 + metadata（user MBTI / 對方 MBTI / 日期）
//   - Body：user / AI 訊息泡泡（user 右、AI 左、簡單灰底配色適合列印）
//   - Footer：Generated by 羽升 AI · timestamp
//   - @media print：A4 size、隱藏「列印」按鈕、優化字體 / 邊距

'use client';

import { useEffect, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp?: string;
}

interface ExportData {
  conversation: {
    id: string;
    topic_title: string | null;
    day_number: number;
    context_type: string;
    messages: ChatMessage[];
    created_at: string;
    updated_at: string;
  };
  user: {
    name: string | null;
    email: string;
    mbti_self: string | null;
  } | null;
  journey: {
    partner_nickname: string | null;
    mbti_partner: string | null;
    relationship_type: string | null;
    round_label: string | null;
    round_number: number | null;
  } | null;
  course: {
    theme: string;
    subtitle: string;
    knowledge_point: string;
  } | null;
}

// 偵測 AI trigger prompt（v1.3.2b.3 一致）
// Bug fix: Day 0 trigger 開頭到「請」約 50 字、原 {0,30} regex 太緊抓不到、放寬至 200
function isAITriggerPrompt(msg: ChatMessage): boolean {
  if (msg.role !== 'user') return false;
  const content = msg.content || '';
  return /^今天是.{0,200}請/.test(content);
}

function formatDate(iso: string | undefined): string {
  if (!iso) return '';
  try {
    const d = new Date(iso);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')} ${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
  } catch {
    return iso;
  }
}

export default function ExportConversationPage() {
  const params = useParams<{ id: string }>();
  const searchParams = useSearchParams();
  const autoprint = searchParams.get('autoprint') === '1';

  const [data, setData] = useState<ExportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch(`/api/conversation/${params.id}`);
        const json = await res.json();
        if (!res.ok || !json.data) {
          setError(json.error || '載入失敗');
          return;
        }
        setData(json.data);
      } catch (err) {
        console.error('[export/load]', err);
        setError('載入失敗');
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [params.id]);

  // Auto-print 在 data load 完後 trigger
  useEffect(() => {
    if (autoprint && data && !loading) {
      const t = setTimeout(() => window.print(), 500);
      return () => clearTimeout(t);
    }
  }, [autoprint, data, loading]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center text-gray-400">
        載入中⋯
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="min-h-screen flex items-center justify-center text-red-500">
        {error || '找不到對話'}
      </div>
    );
  }

  const { conversation, user, journey, course } = data;
  const isPractice = conversation.context_type !== 'consultant';
  const title = isPractice
    ? `Day ${conversation.day_number}${course ? ` — ${course.theme}` : ''}`
    : (conversation.topic_title || '諮詢主題');
  const subtitle = isPractice && course ? course.subtitle : '我卡住了，幫我拆';

  // Filter trigger prompts
  const messages = (conversation.messages || []).filter(m => !isAITriggerPrompt(m));

  return (
    <div className="export-page bg-white text-gray-800 min-h-screen">
      {/* Print/global styles */}
      <style jsx global>{`
        @page {
          size: A4;
          margin: 1.5cm 1.5cm;
        }
        body {
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang TC", "Microsoft JhengHei", sans-serif;
        }
        @media print {
          .no-print { display: none !important; }
          .export-page { padding: 0 !important; }
          .msg-bubble { page-break-inside: avoid; }
          .header-card { page-break-after: avoid; }
        }
      `}</style>

      {/* Toolbar (non-print) */}
      <div className="no-print sticky top-0 bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between shadow-sm">
        <div className="text-sm text-gray-600">
          📄 對話匯出預覽 — 按下 <kbd className="px-1.5 py-0.5 bg-gray-100 border border-gray-300 rounded text-xs">Cmd</kbd>+<kbd className="px-1.5 py-0.5 bg-gray-100 border border-gray-300 rounded text-xs">P</kbd>（Mac）或 <kbd className="px-1.5 py-0.5 bg-gray-100 border border-gray-300 rounded text-xs">Ctrl</kbd>+<kbd className="px-1.5 py-0.5 bg-gray-100 border border-gray-300 rounded text-xs">P</kbd>（Windows）另存為 PDF
        </div>
        <button
          onClick={() => window.print()}
          className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700"
        >
          🖨️ 列印 / 存 PDF
        </button>
      </div>

      <div className="max-w-[760px] mx-auto px-8 py-8">
        {/* Header card */}
        <div className="header-card mb-6 pb-4 border-b-2 border-gray-200">
          <div className="flex items-center gap-2 text-xs text-indigo-600 font-semibold mb-1">
            <span>🕊️</span>
            <span>羽升幸福關係練習</span>
          </div>
          <h1 className="text-2xl font-bold text-gray-900 leading-tight mt-2">
            {title}
          </h1>
          <p className="text-sm text-gray-500 mt-1">{subtitle}</p>

          {/* Metadata grid */}
          <div className="grid grid-cols-2 gap-x-6 gap-y-1 mt-4 text-xs text-gray-600">
            {user?.name && <div><span className="text-gray-400">學員：</span>{user.name}</div>}
            {user?.mbti_self && <div><span className="text-gray-400">你的 MBTI：</span>{user.mbti_self}</div>}
            {journey?.partner_nickname && (
              <div><span className="text-gray-400">對方：</span>{journey.partner_nickname}</div>
            )}
            {journey?.mbti_partner && (
              <div><span className="text-gray-400">對方 MBTI：</span>{journey.mbti_partner}</div>
            )}
            {journey?.round_label && (
              <div className="col-span-2"><span className="text-gray-400">任務：</span>{journey.round_label}</div>
            )}
            <div><span className="text-gray-400">建立時間：</span>{formatDate(conversation.created_at)}</div>
            <div><span className="text-gray-400">最後更新：</span>{formatDate(conversation.updated_at)}</div>
          </div>
        </div>

        {/* Messages */}
        <div className="space-y-4">
          {messages.length === 0 ? (
            <div className="text-center text-gray-400 py-12">這個對話沒有訊息</div>
          ) : (
            messages.map((msg, i) => (
              <div
                key={i}
                className={`msg-bubble flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                {msg.role === 'assistant' && (
                  <div className="w-7 h-7 rounded-full bg-indigo-100 flex items-center justify-center mr-2 shrink-0 text-sm">
                    {isPractice ? '🕊️' : '🤝'}
                  </div>
                )}
                <div
                  className={`max-w-[78%] px-4 py-2.5 rounded-2xl text-sm leading-relaxed whitespace-pre-wrap break-words ${
                    msg.role === 'user'
                      ? 'bg-indigo-100 text-gray-800 rounded-br-sm'
                      : 'bg-gray-100 text-gray-800 rounded-bl-sm'
                  }`}
                >
                  {msg.content}
                </div>
              </div>
            ))
          )}
        </div>

        {/* Footer */}
        <div className="mt-10 pt-4 border-t border-gray-200 text-xs text-gray-400 text-center">
          Generated by 羽升 AI · {formatDate(new Date().toISOString())}
          <br />
          共 {messages.length} 則訊息
        </div>
      </div>
    </div>
  );
}
